
video_list:
    pattern: /video
    defaults: {_controller:   "Video\Controllers\VideoController::index"  }
    methods: GET
video_create:
    pattern: /video
    defaults: {_controller: "Video\Controllers\VideoController::create" }
    methods: POST
video_by_id:
    pattern: /video/{id}
    defaults: {_controller: "Video\Controllers\VideoController::getById" }
    methods: GET
    requirements:
        id: \d+
video_by_title:
    pattern: /video/{title}
    defaults: {_controller: "Video\Controllers\VideoController::getByTitle" }
    methods: GET
video_update:
    pattern: /video/{id}
    defaults: {_controller: "Video\Controllers\VideoController::update"}
    methods: PUT
    requirements:
        id: \d+
video_delete:
    defaults: {_controller: "Video\Controllers\VideoController::delete"}
    pattern: /video/{id}
    methods: DELETE
    requirements:
        id: \d+
playlist_list:
    pattern: /playlist
    defaults: {_controller: "Video\Controllers\PlaylistController::index"}
    methods: GET
playlist_create:
    pattern: /playlist
    methods: POST
    defaults: {_controller: "Video\Controllers\PlaylistController::create"}
playlist_by_id:
    pattern: /playlist/{id}
    methods: GET
    defaults: {_controller: "Video\Controllers\PlaylistController::by_id"}
    requirements:
        id: \d+
playlist_by_title:
    pattern: /playlist/{title}
    methods: GET
    defaults: {_controller: "Video\Controllers\PlaylistController::by_title"}
playlist_update:
    pattern: /playlist/{id}
    methods: PUT
    defaults: {_controller: "Video\Controllers\PlaylistController::update"}
playlist_delete:
    pattern: /playlist/{id}
    defaults: {_controller: "Video\Controllers\PlaylistController::delete"}
tag_list:
    pattern: /tag
    defaults: {_controller: "Video\Controllers\TagController::index"}
tag_by_label:
    pattern: /tag
    defaults: {_controller: "Video\Controllers\TagController::by_label"}
test_user_validation:
    pattern: /test/validation/user
    defaults: {_controller: "Video\Controllers\TestController::userValidation"}
test_email_validation:
    pattern: /test/validation/{email}
    defaults: {_controller: "Video\Controllers\TestController::validation"}

