Video\Entities\Role:
    type: entity
    table: roles
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        label:
            type: string
    oneToMany:
        users:
            targetEntity: Video\Entities\User
            mappedBy: role
            cascade: ["persist","merge"]
        