Video\Entities\Tag:
    type: entity
    table: tags
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
    manyToOne:
        video:
            targetEntity: Video\Entities\Video
            inversedBy: tags
             
