Video\Entities\Playlist:
    type: entity
    table: playlists
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
        description:
            type: string
            length: 512
        image:
            type: string
            length: 256
