Video\Entities\PlaylistVideoRelation:
    type: entity
    table: playlist_video_relation
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        order:
            type: integer
        created_at:
            type: date
    oneToOne:
        playlist:
            targetEntity: Video\Entities\Playlist
            joinColumn:
                name: playlist_id
                referencedColumnName: id
            cascade: ["persist","merge","remove"]
        video:
            targetEntity: Video\Entities\Video
            joinColumn: 
                name: video_id
                referencedColumnName: id
            cascade: ["persist","merge","remove"]
        